version: '2'

services:
  asterisk:
    build:
      context: .
      target: asterisk
    volumes:
      - ./docker_config:/config
    links:
      - "python:python"
    ports:
      - "5060:5060/udp"
  python:
    build:
      context: .
      target: python

    ports:
      - "4574:4574"
